### ISSUE TITLE
Remove Data-mining-with-HTTPAdapter script ?

### ISSUE THREAD

**Issue by adecler** [BHoM/samples#40]
The script freezes Grasshopper even when I lock the solver before opening it.
I am also not sure why this is in the Mongo_Toolkit folder.

Edit: my bad. the script no loading was due to a problem with the installer, not the script. 
My question regarding the location of this file still stands though. I don't think we should have a script with Mongo that requires people to set up their own local mongo server. So should this be purely about the HTTP adapter ?

**Comment by epignatelli** [comment]
Hi Arnaud! 

The reason this is in the MongoAdapter folder is because if uses the `Move` method to pull data using the HTTPAdapter and Push it using a MongoAdapter.

Maybe a folder that contains examples that show interactions between multiple toolkit may be better?
Otherwise, happy for this to be into an HTTPAdatper folder.

@enarhi FYI
